linters:
  Comment:
    enabled: false
  SelectorFormat:
    enabled: true
    convention: BEM
  NestingDepth:
    enabled: true
    max_depth: 4
  PropertySortOrder:
    order: concentric
  SpaceAfterComma:
    exclude:
      - 'app/sass/modules/fonts.scss'
  ColorVariable:
    exclude:
      - 'app/sass/modules/colors.scss'
