linters:
  Comment:
    enabled: false
  SelectorFormat:
    enabled: true
    convention: BEM
  NestingDepth:
    enabled: true
    max_depth: 4
  PropertySortOrder:
    order: concentric
  SpaceAfterComma:
    enabled: true
